## 인스턴스 내의 저장 필요

services:
  greening-server:
    image: "${DOCKERHUB_USERNAME}/greening"
    ports:
      - 8080:8080
    environment:
      TZ: Asia/Seoul
      REDIS_SERVER: "${secrets.REDIS_SERVER}"
      DB_URL: "${secrets.DB_URL}"
      DB_USERNAME: "${secrets.DB_USERNAME}"
      DB_PASSWORD: "${secrets.DB_PASSWORD}"
      JWT_SECRET: "${secrets.JWT_SECRET}"
      KAKAO_CLIENT_ID: "${secrets.KAKAO_CLIENT_ID}"
      GOOGLE_CLIENT_ID: "${secrets.GOOGLE_CLIENT_ID}"
      GOOGLE_CLIENT_SECRET: "${secrets.GOOGLE_CLIENT_SECRET}"
      S3_REGION: "${secrets.S3_REGION}"
      S3_BUCKET: "${secrets.S3_BUCKET}"
      S3_STORAGE_ACCESS_KEY: "${secrets.S3_STORAGE_ACCESS_KEY}"
      S3_STORAGE_SECRET_KEY: "${secrets.S3_STORAGE_SECRET_KEY}"
      S3_BASE_URL: "${secrets.S3_BASE_URL}"
    depends_on:
      redis:
        condition: service_started

  redis:
    image: redis
    ports:
      - 6379:6379
