spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/greening
    username: root
    password: 1234

  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true

jwt:
  access-expiry-time: 1440  # 24시간
  client-secret: f60b1785232c0e9bc42e687d4d2d5c369ab4122c4c8cded1baaf6ae9ef00f01b  # 32바이트 문자열