spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  servlet:
    multipart:
      # 개별 파일 최대 크기
      max-file-size: 10MB
      # 전체 요청의 최대 크기
      max-request-size: 20MB

jwt:
  access-expiry-time: 1440
  client-secret: ${JWT_SECRET}

oauth:
  kakao:
    token_base_url: https://kauth.kakao.com/oauth/token
    user_info_base_url: https://kapi.kakao.com/v2/user/me
    security:
      client_id: ${KAKAO_CLIENT_ID}
      grant_type: authorization_code
  google:
    token_base_url: https://oauth2.googleapis.com/token
    user_info_base_url: https://www.googleapis.com/oauth2/v2/userinfo
    security:
      client_id: ${GOOGLE_CLIENT_ID}
      client_secret: ${GOOGLE_CLIENT_SECRET}
      grant_type: authorization_code

s3:
  storage:
    region: ${S3_REGION}
    bucket: ${S3_BUCKET}
    access-key: ${S3_STORAGE_ACCESS_KEY}
    secret-key: ${S3_STORAGE_SECRET_KEY}
    base-url: ${S3_BASE_URL}
